package com.androidex.capbox.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.androidex.capbox.db.DeviceInfo;
import com.androidex.capbox.db.Note;
import com.androidex.capbox.db.ChatRecord;

import com.androidex.capbox.db.DeviceInfoDao;
import com.androidex.capbox.db.NoteDao;
import com.androidex.capbox.db.ChatRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceInfoDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig chatRecordDaoConfig;

    private final DeviceInfoDao deviceInfoDao;
    private final NoteDao noteDao;
    private final ChatRecordDao chatRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceInfoDaoConfig = daoConfigMap.get(DeviceInfoDao.class).clone();
        deviceInfoDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        chatRecordDaoConfig = daoConfigMap.get(ChatRecordDao.class).clone();
        chatRecordDaoConfig.initIdentityScope(type);

        deviceInfoDao = new DeviceInfoDao(deviceInfoDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        chatRecordDao = new ChatRecordDao(chatRecordDaoConfig, this);

        registerDao(DeviceInfo.class, deviceInfoDao);
        registerDao(Note.class, noteDao);
        registerDao(ChatRecord.class, chatRecordDao);
    }
    
    public void clear() {
        deviceInfoDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        chatRecordDaoConfig.clearIdentityScope();
    }

    public DeviceInfoDao getDeviceInfoDao() {
        return deviceInfoDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ChatRecordDao getChatRecordDao() {
        return chatRecordDao;
    }

}
